[project]
name = "app-suivit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb==0.8.1",
    "faker==19.3.1",
    "streamlit==1.26.0",
]
